### PR TITLE
Fixes for 5.24 lexical clash

### PR DESCRIPTION
**Pull request by rurban**
move the lexicals outside

### CODE REVIEW

**Comment by plicease** [comment]
This PR would be a lot stronger if you provided some context, like how this change will fix failures in existing p5p Perl + CPAN code, or how it will benefit new code going forward.

Also I don't like having lexicals my'd outside of the only block they are being used into a broader scope, so you will have to convince me that is useful as well.

**Comment by rurban** [comment]
Please test it with a new perl >=5.24. It will fail, as perl5 restricted the usage of ambiguous lexicals.
This PR just fixes the failure with newer perls.

**Comment by plicease** [comment]
It is tested on 5.24 for every commit:

https://travis-ci.org/plicease/Test-Script/jobs/201253863

also works with me for my dev Perl:

```
twin% perl -v

This is perl 5, version 25, subversion 6 (v5.25.6) built for x86_64-linux-thread-multi

Copyright 1987-2016, Larry Wall

Perl may be copied only under the terms of either the Artistic License or the
GNU General Public License, which may be found in the Perl 5 source kit.

Complete documentation for Perl, including FAQ lists, should be found on
this system using "man perl" or "perldoc perl".  If you have access to the
Internet, point your browser at http://www.perl.org/, the Perl Home Page.

twin% perl -Ilib t/06_exception.t 
1..2
# Subtest: script_compiles
    ok 1 - Test '' completed
    ok 2 - Test '' no premature diagnostication
    ok 3 - Test '' result count
    ok 4 - subtest 'Script t/bin/missing.pl compiles' of '' compare ok
    ok 5 - subtest 'Script t/bin/missing.pl compiles' of '' compare name
    ok 6 - checking depth
    # 2 - Can't open perl script "t/bin/missing.pl": No such file or directory
    1..6
ok 1 - script_compiles
# Subtest: script_runs
    ok 1 - Test '' completed
    ok 2 - Test '' no premature diagnostication
    ok 3 - Test '' result count
    ok 4 - subtest 'Script t/bin/missing.pl runs' of '' compare ok
    ok 5 - subtest 'Script t/bin/missing.pl runs' of '' compare name
    ok 6 - checking depth
    # 2 - Can't open perl script "t/bin/missing.pl": No such file or directory
    1..6
ok 2 - script_runs
```

**Comment by rurban** [comment]
Interesting, thanks. I"ll recheck

**Comment by rurban** [comment]
Indeed this PR is completely bogus. Please forget about it. Only the other #11 is needed, only for cperl. And there it's an internal cperl bug.

**Pull request closed without merging**
