### PR TITLE
Document in the POD when functions and options were added GH#30

### LINKED ISSUE #30: Documentation should display which versions have which features
If it explicitly requires Test2::V0 instead of (older versions of) Test::More, then the SYNOPSIS should be updated:
```perl
use Test2::V0;
use Test::Script 1.23;
 
script_compiles('script/myscript.pl');
script_runs(['script/myscript.pl', '--my-argument']);
 
done_testing;
```

### PR DESCRIPTION
**Pull request by robrwo**
This fixes #30

### CODE REVIEW

**Comment by plicease** [comment]
Can you please rebase onto the `main` branch.  That should fix the CI errors that were just fixed.

**Comment by robrwo** [comment]
> Can you please rebase onto the `main` branch. That should fix the CI errors that were just fixed in the `main` branch.

Rebased on main

**Comment by plicease** [comment]
> > Can you please rebase onto the `main` branch. That should fix the CI errors that were just fixed in the `main` branch.
> 
> Rebased on main

Awesome thanks.  Merged.

**Comment by plicease** [comment]
Released as 1.27.  No functional changes in this release really, but those browsing metacpan will get the benefit.

**Pull request merged**
